spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:41194/accounts_prod_db
    username: ${DB_USERNAME:?Please set DB_USERNAME env variable}
    password: ${DB_PASSWORD:?Please set DB_PASSWORD env variable}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

build:
  version: "PROD"

accounts:
  message: "Welcome to CentralBank Account APIs (Production)"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@centralbank.com"