build:
  version: "LOCAL"

accounts:
  message: "Welcome to CentralBank Accounts APIs (Local)"
  contactDetails:
    name: "Local Dev Team"
    email: "dev@centralbank.com"
  onCallSupport:
    - "(111) 111-1111"
    - "(222) 222-2222"