spring:
  config:
    activate:
      on-profile: qa

  datasource:
    url: jdbc:postgresql://localhost:41194/loans_qa_db
    username: ${DB_USERNAME:?Please set DB_USERNAME env variable}
    password: ${DB_PASSWORD:?Please set DB_PASSWORD env variable}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "QA"

loans:
  message: "Welcome to CentralBank Loans APIs (QA)"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@centralbank.com"
